name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # Gera a cada 12 horas
  workflow_dispatch:          # Permite rodar manualmente
  push:                       # Atualiza ao fazer push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a snake (contribuições)
        uses: Platane/snk@v3
        with:
          github_user_name: IrannHerbert
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publicar arquivo na branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
